/-
This file was generated by Aristotle (https://aristotle.harmonic.fun),
and modified to fix several issues using gpt-5.3-codex.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2f428d45-058f-449f-9c7d-fd3d54c2ed4b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the proof that the limit of the growth rate of 3AP-free permutations, $\lim_{n\to\infty}\theta(n)^{1/n}$, does not exist.
The proof is conditional on:
1. Sharma's bound: $\theta(2k) \le 21 \theta(k)^2$ for $k \ge 1$.
2. The positivity of $\theta(n)$ (which is known to be true, e.g., $\theta(n) \ge 2^{n-1}$).
3. The computed values of $\theta(64)$ and $\theta(75)$.

The formalization defines the subsequences $b_t(m) = \theta(m 2^t)^{1/(m 2^t)}$, proves their convergence to limits $L_m$, establishes bounds for $L_m$, and demonstrates that $L_1 > L_{75}$, leading to a contradiction if the global limit were to exist.
-/


import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A permutation is 3AP-free if no three indices i < j < k form an arithmetic progression in value. theta(n) is the number of such permutations.
-/
def IsThreeAPFree {n : ℕ} (p : Equiv.Perm (Fin n)) : Prop :=
  ∀ i j k : Fin n, i < j → j < k → (p i : ℕ) + p k ≠ 2 * p j

noncomputable def theta (n : ℕ) : ℕ :=
  Fintype.card { p : Equiv.Perm (Fin n) // IsThreeAPFree p }

/-
Equivalence between `Fin k ⊕ Fin k` and `Fin (2 * k)` mapping left to evens and right to odds.
-/
def equivEvenOdd (k : ℕ) : Fin k ⊕ Fin k ≃ Fin (2 * k) :=
  { toFun := fun x => match x with
      | Sum.inl i => ⟨2 * i.val, by
        -- Since $i$ is a Fin $k$, its value is between $0$ and $k-1$. Multiplying by $2$ gives $2*i.val$ which is between $0$ and $2k-2$. Since $k$ is a natural number, $2k$ is definitely larger than $2k-2$, so $2*i.val < 2k$.
        apply mul_lt_mul_of_pos_left; exact Fin.is_lt i; exact zero_lt_two⟩
      | Sum.inr i => ⟨2 * i.val + 1, by
        linarith [ Fin.is_lt i ]⟩
    invFun := fun i => if h : i.val % 2 = 0 then
        Sum.inl ⟨i.val / 2, by
          linarith [ Nat.mod_add_div i 2, Fin.is_lt i ]⟩
      else
        Sum.inr ⟨i.val / 2, by
          grind⟩
    left_inv := by
      intro i; rcases i with ( _ | _ ) <;> simp +decide [ Nat.add_mod ] ;
      norm_num [ Nat.add_div ]
    right_inv := by
      intro x; cases x ; simp +decide;
      split_ifs <;> simp_all +decide;
      · grind;
      · omega }

/-
Equivalence between `Fin (2 * k)` and `Fin (k + k)` via `Nat.two_mul`.
-/
def cast2k (k : ℕ) : Fin (2 * k) ≃ Fin (k + k) :=
  finCongr (Nat.two_mul k)

/-
Constructs two permutations of size 2k from two permutations of size k.
`constructPerm1` maps the first half to evens (using p) and the second half to odds (using q).
`constructPerm2` maps the first half to odds (using q) and the second half to evens (using p).
-/
def constructPerm1 {k : ℕ} (p q : Equiv.Perm (Fin k)) : Equiv.Perm (Fin (2 * k)) :=
  let e1 : Fin (2 * k) ≃ Fin (k + k) := cast2k k
  let e2 : Fin (k + k) ≃ Fin k ⊕ Fin k := (finSumFinEquiv (m := k) (n := k)).symm
  let e3 : Fin k ⊕ Fin k ≃ Fin k ⊕ Fin k := Equiv.sumCongr p q
  let e4 : Fin k ⊕ Fin k ≃ Fin (2 * k) := equivEvenOdd k
  e1.trans (e2.trans (e3.trans e4))

def constructPerm2 {k : ℕ} (p q : Equiv.Perm (Fin k)) : Equiv.Perm (Fin (2 * k)) :=
  let e1 : Fin (2 * k) ≃ Fin (k + k) := cast2k k
  let e2 : Fin (k + k) ≃ Fin k ⊕ Fin k := (finSumFinEquiv (m := k) (n := k)).symm
  let e3 : Fin k ⊕ Fin k ≃ Fin k ⊕ Fin k := Equiv.sumCongr p q
  let e4 : Fin k ⊕ Fin k ≃ Fin k ⊕ Fin k := Equiv.sumComm (Fin k) (Fin k)
  let e5 : Fin k ⊕ Fin k ≃ Fin (2 * k) := equivEvenOdd k
  e1.trans (e2.trans (e3.trans (e4.trans e5)))

/-
Characterization of `constructPerm1` on the first half of the domain.
It maps the i-th element of the first half to 2 * p(i).
-/
lemma constructPerm1_apply_left {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin k) :
    (constructPerm1 p q ((cast2k k).symm (Fin.castAdd k i)) : ℕ) = 2 * (p i : ℕ) := by
  simp [constructPerm1, cast2k, equivEvenOdd, finSumFinEquiv]

/-
Characterization of `constructPerm1` on the second half of the domain.
It maps the i-th element of the second half to 2 * q(i) + 1.
-/
lemma constructPerm1_apply_right {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin k) :
    (constructPerm1 p q ((cast2k k).symm (Fin.natAdd k i)) : ℕ) = 2 * (q i : ℕ) + 1 := by
  simp [constructPerm1, cast2k, equivEvenOdd, finSumFinEquiv, Fin.addNat, Fin.addCases]

/-
The value of `constructPerm1` is even if and only if the index is in the first half.
-/
lemma constructPerm1_parity {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) :
    (constructPerm1 p q i : ℕ) % 2 = 0 ↔ (i : ℕ) < k := by
  -- We can split i into two cases: i < k and i >= k.
  -- Or use Fin.addCases.
  -- By definition of `constructPerm1`, we consider two cases: when `i` is in the first `k` elements (i < k) and when it's in the next `k` elements (i ≥ k).
  by_cases h_case : i.val < k;
  · -- Since `i` is in the first `k` elements, we have `i = Fin.castAdd k i`.
    obtain ⟨i', hi'⟩ : ∃ i' : Fin k, i = (cast2k k).symm (Fin.castAdd k i') := by
      use ⟨i.val, by linarith⟩;
      have h1 : (cast2k k) i = Fin.castAdd k ⟨(i : ℕ), h_case⟩ := by
        apply Fin.ext
        simp [cast2k]
      have h2 :
          (cast2k k) ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h_case⟩)) =
          Fin.castAdd k ⟨(i : ℕ), h_case⟩ := by
        exact (cast2k k).apply_symm_apply (Fin.castAdd k ⟨(i : ℕ), h_case⟩)
      exact (cast2k k).injective (h1.trans h2.symm)
    rw [ hi', constructPerm1_apply_left ] ; norm_num [ Nat.add_mod, Nat.mul_mod ];
    convert h_case using 1;
    exact hi'.symm ▸ rfl;
  · -- Since $i \geq k$, we can write $i = k + m$ for some $m$.
    obtain ⟨m, hm⟩ : ∃ m : Fin k, i = (cast2k k).symm (Fin.natAdd k m) := by
      let m : Fin k := ⟨i.val - k, by omega⟩
      use m
      have h_ge : k ≤ (i : ℕ) := Nat.le_of_not_lt h_case
      have h1 : (cast2k k) i = Fin.natAdd k m := by
        apply Fin.ext
        simp [Fin.natAdd, cast2k, m, Nat.add_sub_cancel' h_ge]
      have h2 :
          (cast2k k) ((cast2k k).symm (Fin.natAdd k m)) =
          Fin.natAdd k m := by
        exact (cast2k k).apply_symm_apply (Fin.natAdd k m)
      exact (cast2k k).injective (h1.trans h2.symm)
    rw [ hm, constructPerm1_apply_right ] ; simp +decide [ Nat.add_mod ] ; aesop

/-
If two values of `constructPerm1` have the same parity, then their indices are either both in the first half or both in the second half.
-/
lemma constructPerm1_same_half {k : ℕ} (p q : Equiv.Perm (Fin k)) (i l : Fin (2 * k)) :
    (constructPerm1 p q i : ℕ) % 2 = (constructPerm1 p q l : ℕ) % 2 → ((i : ℕ) < k ↔ (l : ℕ) < k) := by
      intro h; have := constructPerm1_parity p q i; have := constructPerm1_parity p q l; aesop;

/-
Helper lemma: for i < k, constructPerm1 p q i = 2 * p(i).
-/
lemma constructPerm1_val_lt {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) (h : (i : ℕ) < k) :
    (constructPerm1 p q i : ℕ) = 2 * (p ⟨i, h⟩ : ℕ) := by
  have hi : i = (cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩) := by
    have h1 : (cast2k k) i = Fin.castAdd k ⟨(i : ℕ), h⟩ := by
      apply Fin.ext
      simp [cast2k]
    have h2 :
        (cast2k k) ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩)) =
        Fin.castAdd k ⟨(i : ℕ), h⟩ := by
      exact (cast2k k).apply_symm_apply (Fin.castAdd k ⟨(i : ℕ), h⟩)
    exact (cast2k k).injective (h1.trans h2.symm)
  have hval :
      (constructPerm1 p q i : ℕ) =
        (constructPerm1 p q ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩)) : ℕ) := by
    exact congrArg (fun x => (constructPerm1 p q x : ℕ)) hi
  exact hval.trans (constructPerm1_apply_left p q ⟨(i : ℕ), h⟩)

lemma constructPerm1_val_ge {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) (h : k ≤ (i : ℕ)) :
    (constructPerm1 p q i : ℕ) = 2 * (q ⟨(i : ℕ) - k, by omega⟩ : ℕ) + 1 := by
  let m : Fin k := ⟨(i : ℕ) - k, by omega⟩
  have hi : i = (cast2k k).symm (Fin.natAdd k m) := by
    have h1 : (cast2k k) i = Fin.natAdd k m := by
      apply Fin.ext
      simp [Fin.natAdd, cast2k, m, Nat.add_sub_cancel' h]
    have h2 :
        (cast2k k) ((cast2k k).symm (Fin.natAdd k m)) =
        Fin.natAdd k m := by
      exact (cast2k k).apply_symm_apply (Fin.natAdd k m)
    exact (cast2k k).injective (h1.trans h2.symm)
  have hval :
      (constructPerm1 p q i : ℕ) =
        (constructPerm1 p q ((cast2k k).symm (Fin.natAdd k m)) : ℕ) := by
    exact congrArg (fun x => (constructPerm1 p q x : ℕ)) hi
  have hm : (constructPerm1 p q ((cast2k k).symm (Fin.natAdd k m)) : ℕ) = 2 * (q m : ℕ) + 1 :=
    constructPerm1_apply_right p q m
  simpa [m] using hval.trans hm

/-
If p and q are 3AP-free, then constructPerm1 p q is 3AP-free.
Proof uses parity argument to show indices must be in same half, then reduces to 3AP-free property of p or q.
-/
lemma constructPerm1_isThreeAPFree {k : ℕ} (p q : Equiv.Perm (Fin k))
    (hp : IsThreeAPFree p) (hq : IsThreeAPFree q) :
    IsThreeAPFree (constructPerm1 p q) := by
      intro a b c hab hbc;
      -- By Lemma `constructPerm1_same_half`, we know that either both `a` and `c` are in the first half or both are in the second half.
      by_cases ha : (a : ℕ) < k ∧ (c : ℕ) < k ∨ (a : ℕ) ≥ k ∧ (c : ℕ) ≥ k;
      · -- By Lemma `constructPerm1_same_half`, we know that either both `a` and `c` are in the first half or both are in the second half. Let's consider the two cases.
        cases' ha with ha ha;
        · -- By Lemma `constructPerm1_val_lt`, we know that `constructPerm1 p q a = 2 * p ⟨a, ha.left⟩` and `constructPerm1 p q c = 2 * p ⟨c, ha.right⟩`.
          have hb : (b : ℕ) < k := by linarith [show (b : ℕ) < c from hbc, ha.2]
          have ha_val : (constructPerm1 p q a : ℕ) = 2 * (p ⟨a, ha.1⟩ : ℕ) := constructPerm1_val_lt p q a ha.1
          have hb_val : (constructPerm1 p q b : ℕ) = 2 * (p ⟨b, hb⟩ : ℕ) := constructPerm1_val_lt p q b hb
          have hc_val : (constructPerm1 p q c : ℕ) = 2 * (p ⟨c, ha.2⟩ : ℕ) := constructPerm1_val_lt p q c ha.2
          intro h
          apply hp ⟨a, ha.1⟩ ⟨b, hb⟩ ⟨c, ha.2⟩
          · simpa [Fin.ext_iff] using hab
          · simpa [Fin.ext_iff] using hbc
          · linarith [h, ha_val, hb_val, hc_val]
        · -- By Lemma `constructPerm1_same_half`, we know that either both `a` and `c` are in the first half or both are in the second half. Let's consider the case where both `a` and `c` are in the second half.
          have ha_ge : (a : ℕ) ≥ k := ha.1
          have hc_ge : (c : ℕ) ≥ k := ha.2
          have hb_ge : (b : ℕ) ≥ k := by linarith [show (a : ℕ) < b from hab, ha_ge]
          have h_second_half :
              (constructPerm1 p q a : ℕ) = 2 * (q ⟨(a : ℕ) - k, by omega⟩ : ℕ) + 1 ∧
              (constructPerm1 p q c : ℕ) = 2 * (q ⟨(c : ℕ) - k, by omega⟩ : ℕ) + 1 := by
            exact ⟨constructPerm1_val_ge p q a ha_ge, constructPerm1_val_ge p q c hc_ge⟩
          have h_second_half_b :
              (constructPerm1 p q b : ℕ) = 2 * (q ⟨(b : ℕ) - k, by omega⟩ : ℕ) + 1 :=
            constructPerm1_val_ge p q b hb_ge
          have hq_main :
              (q ⟨(a : ℕ) - k, by omega⟩ : ℕ) + (q ⟨(c : ℕ) - k, by omega⟩ : ℕ) ≠
                2 * (q ⟨(b : ℕ) - k, by omega⟩ : ℕ) := by
            apply hq ⟨(a : ℕ) - k, by omega⟩ ⟨(b : ℕ) - k, by omega⟩ ⟨(c : ℕ) - k, by omega⟩
            · exact (tsub_lt_tsub_iff_right ha_ge).2 (by simpa using hab)
            · exact (tsub_lt_tsub_iff_right hb_ge).2 (by simpa using hbc)
          intro h
          apply hq_main
          linarith [h, h_second_half.1, h_second_half.2, h_second_half_b]
      · -- By Lemma `constructPerm1_same_half`, we know that either both `a` and `c` are in the first half or both are in the second half. Therefore, we can conclude that `a` and `c` are in different halves.
        by_cases ha : (a : ℕ) < k ∧ (c : ℕ) ≥ k ∨ (a : ℕ) ≥ k ∧ (c : ℕ) < k;
        · cases ha <;> simp_all +decide;
          · -- By Lemma `constructPerm1_parity`, we know that `constructPerm1 p q a` is even and `constructPerm1 p q c` is odd.
            have h_even_odd : (constructPerm1 p q a : ℕ) % 2 = 0 ∧ (constructPerm1 p q c : ℕ) % 2 = 1 := by
              exact ⟨ by simpa using constructPerm1_parity p q a |>.2 ( by aesop ), by simpa using constructPerm1_parity p q c |>.not.mpr ( by aesop ) ⟩;
            omega;
          · linarith [ show ( a : ℕ ) < b from hab, show ( b : ℕ ) < c from hbc ];
        · grind

/-
The value of `constructPerm2` is odd if and only if the index is in the first half.
-/
lemma constructPerm2_apply_left {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin k) :
    (constructPerm2 p q ((cast2k k).symm (Fin.castAdd k i)) : ℕ) = 2 * (p i : ℕ) + 1 := by
  simp [constructPerm2, cast2k, equivEvenOdd, finSumFinEquiv, Fin.addCases]

lemma constructPerm2_apply_right {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin k) :
    (constructPerm2 p q ((cast2k k).symm (Fin.natAdd k i)) : ℕ) = 2 * (q i : ℕ) := by
  simp [constructPerm2, cast2k, equivEvenOdd, finSumFinEquiv, Fin.addNat, Fin.addCases]

lemma constructPerm2_parity {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) :
    (constructPerm2 p q i : ℕ) % 2 = 1 ↔ (i : ℕ) < k := by
  by_cases h_case : (i : ℕ) < k
  · obtain ⟨i', hi'⟩ : ∃ i' : Fin k, i = (cast2k k).symm (Fin.castAdd k i') := by
      use ⟨(i : ℕ), h_case⟩
      have h1 : (cast2k k) i = Fin.castAdd k ⟨(i : ℕ), h_case⟩ := by
        apply Fin.ext
        simp [cast2k]
      have h2 :
          (cast2k k) ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h_case⟩)) =
          Fin.castAdd k ⟨(i : ℕ), h_case⟩ := by
        exact (cast2k k).apply_symm_apply (Fin.castAdd k ⟨(i : ℕ), h_case⟩)
      exact (cast2k k).injective (h1.trans h2.symm)
    rw [hi', constructPerm2_apply_left]
    constructor
    · intro _
      simpa [hi'] using h_case
    · intro _
      norm_num [Nat.add_mod, Nat.mul_mod]
  · obtain ⟨m, hm⟩ : ∃ m : Fin k, i = (cast2k k).symm (Fin.natAdd k m) := by
      let m : Fin k := ⟨(i : ℕ) - k, by omega⟩
      use m
      have h_ge : k ≤ (i : ℕ) := Nat.le_of_not_lt h_case
      have h1 : (cast2k k) i = Fin.natAdd k m := by
        apply Fin.ext
        simp [Fin.natAdd, cast2k, m, Nat.add_sub_cancel' h_ge]
      have h2 :
          (cast2k k) ((cast2k k).symm (Fin.natAdd k m)) =
          Fin.natAdd k m := by
        exact (cast2k k).apply_symm_apply (Fin.natAdd k m)
      exact (cast2k k).injective (h1.trans h2.symm)
    rw [hm, constructPerm2_apply_right]
    constructor
    · intro hmod
      norm_num [Nat.add_mod, Nat.mul_mod] at hmod
    · intro hk
      have h_ge : k ≤ (((cast2k k).symm (Fin.natAdd k m) : Fin (2 * k)) : ℕ) := by
        simpa [hm] using Nat.le_of_not_lt h_case
      exact (False.elim ((Nat.not_lt.mpr h_ge) hk))

/-
Helper lemma: for i < k, constructPerm2 p q i = 2 * p(i) + 1.
-/
lemma constructPerm2_val_lt {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) (h : (i : ℕ) < k) :
    (constructPerm2 p q i : ℕ) = 2 * (p ⟨i, h⟩ : ℕ) + 1 := by
  have hi : i = (cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩) := by
    have h1 : (cast2k k) i = Fin.castAdd k ⟨(i : ℕ), h⟩ := by
      apply Fin.ext
      simp [cast2k]
    have h2 :
        (cast2k k) ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩)) =
        Fin.castAdd k ⟨(i : ℕ), h⟩ := by
      exact (cast2k k).apply_symm_apply (Fin.castAdd k ⟨(i : ℕ), h⟩)
    exact (cast2k k).injective (h1.trans h2.symm)
  have hval :
      (constructPerm2 p q i : ℕ) =
        (constructPerm2 p q ((cast2k k).symm (Fin.castAdd k ⟨(i : ℕ), h⟩)) : ℕ) := by
    exact congrArg (fun x => (constructPerm2 p q x : ℕ)) hi
  exact hval.trans (constructPerm2_apply_left p q ⟨(i : ℕ), h⟩)

lemma constructPerm2_val_ge {k : ℕ} (p q : Equiv.Perm (Fin k)) (i : Fin (2 * k)) (h : k ≤ (i : ℕ)) :
    (constructPerm2 p q i : ℕ) = 2 * (q ⟨(i : ℕ) - k, by omega⟩ : ℕ) := by
  let m : Fin k := ⟨(i : ℕ) - k, by omega⟩
  have hi : i = (cast2k k).symm (Fin.natAdd k m) := by
    have h1 : (cast2k k) i = Fin.natAdd k m := by
      apply Fin.ext
      simp [Fin.natAdd, cast2k, m, Nat.add_sub_cancel' h]
    have h2 :
        (cast2k k) ((cast2k k).symm (Fin.natAdd k m)) =
        Fin.natAdd k m := by
      exact (cast2k k).apply_symm_apply (Fin.natAdd k m)
    exact (cast2k k).injective (h1.trans h2.symm)
  have hval :
      (constructPerm2 p q i : ℕ) =
        (constructPerm2 p q ((cast2k k).symm (Fin.natAdd k m)) : ℕ) := by
    exact congrArg (fun x => (constructPerm2 p q x : ℕ)) hi
  have hm : (constructPerm2 p q ((cast2k k).symm (Fin.natAdd k m)) : ℕ) = 2 * (q m : ℕ) :=
    constructPerm2_apply_right p q m
  simpa [m] using hval.trans hm

/-
If two values of `constructPerm2` have the same parity, then their indices are either both in the first half or both in the second half.
-/
lemma constructPerm2_same_half {k : ℕ} (p q : Equiv.Perm (Fin k)) (i l : Fin (2 * k)) :
    (constructPerm2 p q i : ℕ) % 2 = (constructPerm2 p q l : ℕ) % 2 → ((i : ℕ) < k ↔ (l : ℕ) < k) := by
  intro h
  have hi : (constructPerm2 p q i : ℕ) % 2 = 1 ↔ (i : ℕ) < k := constructPerm2_parity p q i
  have hl : (constructPerm2 p q l : ℕ) % 2 = 1 ↔ (l : ℕ) < k := constructPerm2_parity p q l
  aesop

/-
If p and q are 3AP-free, then constructPerm2 p q is 3AP-free.
Proof uses parity argument to show indices must be in same half, then reduces to 3AP-free property of p or q.
Uses `constructPerm2_same_half`, `constructPerm2_val_lt`, and `constructPerm2_val_ge_correct`.
-/
lemma constructPerm2_isThreeAPFree {k : ℕ} (p q : Equiv.Perm (Fin k))
    (hp : IsThreeAPFree p) (hq : IsThreeAPFree q) :
    IsThreeAPFree (constructPerm2 p q) := by
  intro i l m hi hl
  by_cases h_half : (i : ℕ) < k ∧ (m : ℕ) < k ∨ (i : ℕ) ≥ k ∧ (m : ℕ) ≥ k
  · cases' h_half with h_half h_half
    · have hl_lt : (l : ℕ) < k := by linarith [show (l : ℕ) < m from hl, h_half.2]
      have hi_val : (constructPerm2 p q i : ℕ) = 2 * (p ⟨i, h_half.1⟩ : ℕ) + 1 :=
        constructPerm2_val_lt p q i h_half.1
      have hl_val : (constructPerm2 p q l : ℕ) = 2 * (p ⟨l, hl_lt⟩ : ℕ) + 1 :=
        constructPerm2_val_lt p q l hl_lt
      have hm_val : (constructPerm2 p q m : ℕ) = 2 * (p ⟨m, h_half.2⟩ : ℕ) + 1 :=
        constructPerm2_val_lt p q m h_half.2
      intro h
      apply hp ⟨i, h_half.1⟩ ⟨l, hl_lt⟩ ⟨m, h_half.2⟩
      · simpa [Fin.ext_iff] using hi
      · simpa [Fin.ext_iff] using hl
      · linarith [h, hi_val, hl_val, hm_val]
    · have hl_ge : (l : ℕ) ≥ k := by linarith [show (i : ℕ) < l from hi, h_half.1]
      have hi_val : (constructPerm2 p q i : ℕ) = 2 * (q ⟨(i : ℕ) - k, by omega⟩ : ℕ) :=
        constructPerm2_val_ge p q i h_half.1
      have hl_val : (constructPerm2 p q l : ℕ) = 2 * (q ⟨(l : ℕ) - k, by omega⟩ : ℕ) :=
        constructPerm2_val_ge p q l hl_ge
      have hm_val : (constructPerm2 p q m : ℕ) = 2 * (q ⟨(m : ℕ) - k, by omega⟩ : ℕ) :=
        constructPerm2_val_ge p q m h_half.2
      have hq_main :
          (q ⟨(i : ℕ) - k, by omega⟩ : ℕ) + (q ⟨(m : ℕ) - k, by omega⟩ : ℕ) ≠
            2 * (q ⟨(l : ℕ) - k, by omega⟩ : ℕ) := by
        apply hq ⟨(i : ℕ) - k, by omega⟩ ⟨(l : ℕ) - k, by omega⟩ ⟨(m : ℕ) - k, by omega⟩
        · exact (tsub_lt_tsub_iff_right h_half.1).2 (by simpa using hi)
        · exact (tsub_lt_tsub_iff_right hl_ge).2 (by simpa using hl)
      intro h
      apply hq_main
      linarith [h, hi_val, hl_val, hm_val]
  · rcases lt_or_ge (i : ℕ) k with hi_lt | hi_ge
    · rcases lt_or_ge (m : ℕ) k with hm_lt | hm_ge
      · exact False.elim <| h_half (Or.inl ⟨hi_lt, hm_lt⟩)
      · intro h
        have hi_mod : (constructPerm2 p q i : ℕ) % 2 = 1 := (constructPerm2_parity p q i).2 hi_lt
        have hm_not : (constructPerm2 p q m : ℕ) % 2 ≠ 1 := (constructPerm2_parity p q m).not.mpr (Nat.not_lt.mpr hm_ge)
        have hm_mod : (constructPerm2 p q m : ℕ) % 2 = 0 := Nat.mod_two_ne_one.mp hm_not
        have hsum0 : ((constructPerm2 p q i : ℕ) + (constructPerm2 p q m : ℕ)) % 2 = 0 := by
          calc
            ((constructPerm2 p q i : ℕ) + (constructPerm2 p q m : ℕ)) % 2
                = (2 * (constructPerm2 p q l : ℕ)) % 2 := by simp [h]
            _ = 0 := by simp
        have hsum1 : ((constructPerm2 p q i : ℕ) + (constructPerm2 p q m : ℕ)) % 2 = 1 := by
          simp [Nat.add_mod, hi_mod, hm_mod]
        omega
    · rcases lt_or_ge (m : ℕ) k with hm_lt | hm_ge
      · linarith [show (i : ℕ) < m from lt_trans hi hl]
      · exact False.elim <| h_half (Or.inr ⟨hi_ge, hm_ge⟩)

/-
The map (p, q) -> constructPerm1 p q is injective.
-/
lemma constructPerm1_injective {k : ℕ} :
    Function.Injective (fun (x : Equiv.Perm (Fin k) × Equiv.Perm (Fin k)) => constructPerm1 x.1 x.2) := by
  intro x y h
  apply Prod.ext
  · apply Equiv.Perm.ext
    intro i
    apply Fin.ext
    have hleft :
        (constructPerm1 x.1 x.2 ((cast2k k).symm (Fin.castAdd k i)) : ℕ) =
        (constructPerm1 y.1 y.2 ((cast2k k).symm (Fin.castAdd k i)) : ℕ) := by
      simpa using congrArg
        (fun e : Equiv.Perm (Fin (2 * k)) => (e ((cast2k k).symm (Fin.castAdd k i)) : ℕ)) h
    have hleft' : 2 * (x.1 i : ℕ) = 2 * (y.1 i : ℕ) := by
      simpa [constructPerm1_apply_left] using hleft
    omega
  · apply Equiv.Perm.ext
    intro i
    apply Fin.ext
    have hright :
        (constructPerm1 x.1 x.2 ((cast2k k).symm (Fin.natAdd k i)) : ℕ) =
        (constructPerm1 y.1 y.2 ((cast2k k).symm (Fin.natAdd k i)) : ℕ) := by
      simpa using congrArg
        (fun e : Equiv.Perm (Fin (2 * k)) => (e ((cast2k k).symm (Fin.natAdd k i)) : ℕ)) h
    have hright' : 2 * (x.2 i : ℕ) + 1 = 2 * (y.2 i : ℕ) + 1 := by
      rw [← constructPerm1_apply_right x.1 x.2 i, ← constructPerm1_apply_right y.1 y.2 i]
      exact hright
    omega

/-
The map (p, q) -> constructPerm2 p q is injective.
-/
lemma constructPerm2_injective {k : ℕ} :
    Function.Injective (fun (x : Equiv.Perm (Fin k) × Equiv.Perm (Fin k)) => constructPerm2 x.1 x.2) := by
  intro x y h
  apply Prod.ext
  · apply Equiv.Perm.ext
    intro i
    apply Fin.ext
    have hleft :
        (constructPerm2 x.1 x.2 ((cast2k k).symm (Fin.castAdd k i)) : ℕ) =
        (constructPerm2 y.1 y.2 ((cast2k k).symm (Fin.castAdd k i)) : ℕ) := by
      simpa using congrArg
        (fun e : Equiv.Perm (Fin (2 * k)) => (e ((cast2k k).symm (Fin.castAdd k i)) : ℕ)) h
    have hleft' : 2 * (x.1 i : ℕ) + 1 = 2 * (y.1 i : ℕ) + 1 := by
      rw [← constructPerm2_apply_left x.1 x.2 i, ← constructPerm2_apply_left y.1 y.2 i]
      exact hleft
    omega
  · apply Equiv.Perm.ext
    intro i
    apply Fin.ext
    have hright :
        (constructPerm2 x.1 x.2 ((cast2k k).symm (Fin.natAdd k i)) : ℕ) =
        (constructPerm2 y.1 y.2 ((cast2k k).symm (Fin.natAdd k i)) : ℕ) := by
      simpa using congrArg
        (fun e : Equiv.Perm (Fin (2 * k)) => (e ((cast2k k).symm (Fin.natAdd k i)) : ℕ)) h
    have hright' : 2 * (x.2 i : ℕ) = 2 * (y.2 i : ℕ) := by
      rw [← constructPerm2_apply_right x.1 x.2 i, ← constructPerm2_apply_right y.1 y.2 i]
      exact hright
    omega

/-
constructPerm1 and constructPerm2 produce distinct permutations (for k >= 1).
-/
lemma constructPerm1_ne_constructPerm2 {k : ℕ} (hk : k ≥ 1) (p q p' q' : Equiv.Perm (Fin k)) :
    constructPerm1 p q ≠ constructPerm2 p' q' := by
  intro h
  have h0 : (0 : ℕ) < k := by linarith
  let i : Fin (2 * k) := ⟨0, by linarith⟩
  have h1 : (constructPerm1 p q i : ℕ) % 2 = 0 := by
    rw [constructPerm1_parity]
    exact h0
  have h2 : (constructPerm2 p' q' i : ℕ) % 2 = 1 := by
    rw [constructPerm2_parity]
    exact h0
  rw [h] at h1
  rw [h1] at h2
  contradiction

/-
theta(2k) >= 2 * theta(k)^2 for k >= 1.
-/
lemma theta_two_mul_le (k : ℕ) (hk : k ≥ 1) : 2 * theta k ^ 2 ≤ theta (2 * k) := by
  -- By definition of $theta$, we know that there are at least $theta(k)^2$ 3AP-free permutations of size $2k$.
  have h_count : Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p } ≥ 2 * Fintype.card { p : Equiv.Perm (Fin k) // IsThreeAPFree p } ^ 2 := by
    -- Consider the set of permutations of size $2k$ constructed by `constructPerm1` and `constructPerm2`.
    have h_set : Finset.card (Finset.image (fun (x : Equiv.Perm (Fin k) × Equiv.Perm (Fin k)) => constructPerm1 x.1 x.2) (Finset.univ.filter (fun p : Equiv.Perm (Fin k) => IsThreeAPFree p) ×ˢ Finset.univ.filter (fun q : Equiv.Perm (Fin k) => IsThreeAPFree q))) + Finset.card (Finset.image (fun (x : Equiv.Perm (Fin k) × Equiv.Perm (Fin k)) => constructPerm2 x.1 x.2) (Finset.univ.filter (fun p : Equiv.Perm (Fin k) => IsThreeAPFree p) ×ˢ Finset.univ.filter (fun q : Equiv.Perm (Fin k) => IsThreeAPFree q))) ≤ Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p } := by
      rw [ ← Finset.card_union_of_disjoint ];
      · rw [ Fintype.card_subtype ];
        refine Finset.card_le_card ?_;
        simp +decide [ Finset.subset_iff ];
        rintro x ( ⟨ a, b, ⟨ ha, hb ⟩, rfl ⟩ | ⟨ a, b, ⟨ ha, hb ⟩, rfl ⟩ ) <;> [ exact constructPerm1_isThreeAPFree a b ha hb; exact constructPerm2_isThreeAPFree a b ha hb ];
      · rw [ Finset.disjoint_left ];
        simp +zetaDelta at *;
        rintro a p q hp hq rfl r s hr hs; exact fun h => constructPerm1_ne_constructPerm2 hk p q r s <| h.symm;
    rw [ Finset.card_image_of_injective, Finset.card_image_of_injective ] at h_set;
    · simp_all +decide [ sq, Fintype.card_subtype ];
      grind;
    · exact constructPerm2_injective;
    · exact constructPerm1_injective;
  exact h_count

/-
A type `s` is valid if there exists a 3AP-free permutation `p` such that `p i % 2 = s i` for all `i`.
-/
def ValidType (n : ℕ) (s : Fin n → Fin 2) : Prop :=
  ∃ p : Equiv.Perm (Fin n), IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s i

/-
theta(2k) is the sum over all balanced parity patterns s of the number of 3AP-free permutations with pattern s.
-/
lemma theta_eq_sum_valid_types (k : ℕ) :
    theta (2 * k) = ∑ s : { s : Fin (2 * k) → Fin 2 // (Finset.univ.filter (fun i => s i = 0)).card = k },
      Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s.val i } := by
  -- This is a partition of the set of 3AP-free permutations by their parity pattern.
  -- Each permutation has exactly k even values and k odd values, so its parity pattern s satisfies the condition.
  unfold theta;
  simp +decide only [Fintype.card_subtype];
  rw [ ← Finset.card_biUnion ];
  · congr with x;
    simp +zetaDelta at *;
    intro hx
    use fun i => if (x i).val % 2 = 0 then 0 else 1
    simp;
    have h_card : Finset.card (Finset.filter (fun i : Fin (2 * k) => (x i : ℕ) % 2 = 0) Finset.univ) = Finset.card (Finset.filter (fun i : Fin (2 * k) => i.val % 2 = 0) Finset.univ) := by
      rw [ Finset.card_filter, Finset.card_filter ];
      conv_rhs => rw [ ← Equiv.sum_comp x ] ;
    rw [ h_card ];
    rw [ Finset.card_eq_of_bijective ];
    exact ⟨ rfl, fun i => by cases Nat.mod_two_eq_zero_or_one ( x i : ℕ ) <;> simp +decide [ * ] ⟩;
    use fun i hi => ⟨ 2 * i, by linarith ⟩;
    · exact fun a ha => ⟨ a / 2, Nat.div_lt_of_lt_mul <| by linarith [ Fin.is_lt a ], by congr; linarith [ Nat.mod_add_div a 2, Finset.mem_filter.mp ha ] ⟩;
    · norm_num [ Nat.mul_mod ];
    · aesop;
  · intro x hx y hy hxy; simp_all +decide [ Finset.disjoint_left ] ;
    contrapose! hxy; aesop

/-
Extracts the map on the indices where `s` is 0, dividing values by 2.
-/
def extract_even_map {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k)
    (p : Fin (2 * k) → Fin (2 * k)) : Fin k → Fin k :=
  fun j =>
    let A := Finset.univ.filter (fun i => s i = 0)
    let isoA := A.orderIsoOfFin hs
    let idx := isoA j
    let val := p idx
    ⟨val / 2, by
      have h_lt : (val : ℕ) < 2 * k := val.isLt
      apply Nat.div_lt_of_lt_mul
      exact h_lt⟩

/-
Extracts the map on the indices where `s` is 1, mapping `val` to `(val - 1) / 2`.
-/
def extract_odd_map {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 1)).card = k)
    (p : Fin (2 * k) → Fin (2 * k)) (hp : ∀ i, (p i : ℕ) % 2 = s i) : Fin k → Fin k :=
  fun j =>
    let B := Finset.univ.filter (fun i => s i = 1)
    let isoB := B.orderIsoOfFin hs
    let idx := isoB j
    let val := p idx
    ⟨((val : ℕ) - 1) / 2, by
      have h_odd : (val : ℕ) % 2 = 1 := by
        rw [hp idx]
        have : idx.val ∈ B := idx.prop
        rw [Finset.mem_filter] at this
        have h_eq : s idx = 1 := this.2
        rw [h_eq]
        rfl
      have h_lt : (val : ℕ) < 2 * k := val.isLt
      apply Nat.div_lt_of_lt_mul
      omega⟩

/-
Bundles `extract_even_map` into a permutation `Fin k \simeq Fin k`.
-/
noncomputable def extract_even_perm {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp : ∀ i, (p i : ℕ) % 2 = s i) : Equiv.Perm (Fin k) :=
  Equiv.ofBijective (extract_even_map hs p) (by
  -- To show that `extract_even_map` is injective, assume `extract_even_map hs p j = extract_even_map hs p j'`.
  have h_inj : Function.Injective (extract_even_map hs p) := by
    intro i j hijop;
    -- Since $p$ is a permutation, the restriction of $p$ to $A$ is also a permutation of $A$, and thus the map $extract_even_map$ is injective. Hence, we have $p (isoA i) = p (isoA j)$.
    have h_eq : p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i) = p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j) := by
      have h_eq : (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i) : ℕ) = 2 * (extract_even_map hs p i : ℕ) ∧ (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j) : ℕ) = 2 * (extract_even_map hs p j : ℕ) := by
        have h_eq : ∀ i : Fin k, (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i) : ℕ) % 2 = 0 := by
          grind;
        exact ⟨ by linarith! [ Nat.mod_add_div ( p ( Finset.orderIsoOfFin ( Finset.univ.filter ( fun i => s i = 0 ) ) hs i ) ) 2, h_eq i ], by linarith! [ Nat.mod_add_div ( p ( Finset.orderIsoOfFin ( Finset.univ.filter ( fun i => s i = 0 ) ) hs j ) ) 2, h_eq j ] ⟩;
      exact Fin.ext ( by aesop );
    have := p.injective h_eq; aesop;
  exact ⟨ h_inj, Finite.injective_iff_surjective.mp h_inj ⟩)

/-
`extract_even_map` is injective.
-/
lemma extract_even_map_injective {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp : ∀ i, (p i : ℕ) % 2 = s i) :
    Function.Injective (extract_even_map hs p) := by
      exact Equiv.injective ( extract_even_perm hs p hp )

/-
`extract_odd_map` is injective.
-/
lemma extract_odd_map_injective {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 1)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp : ∀ i, (p i : ℕ) % 2 = s i) :
    Function.Injective (extract_odd_map hs p hp) := by
      -- Assume that extract_odd_map j = extract_odd_map l. This means that the values of p at the indices corresponding to j and l are the same.
      intro j l h_eq
      have h_val : (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 1)) hs j)).val = (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 1)) hs l)).val := by
        unfold extract_odd_map at h_eq;
        grind;
      have := p.injective ( Fin.ext h_val ) ; aesop;

/-
The permutation extracted from the even values is 3AP-free.
-/
lemma extract_even_map_isThreeAPFree {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp_free : IsThreeAPFree p) (hp_parity : ∀ i, (p i : ℕ) % 2 = s i) :
    IsThreeAPFree (extract_even_perm hs p hp_parity) := by
  intro i j l hij hjl h_eq
  -- We need to show that if i, j, l form a 3AP in the extracted permutation, then they correspond to a 3AP in p.
  -- Let A be the set of indices where s i = 0.
  -- Let isoA be the order isomorphism from Fin k to A.
  -- Let idx_i = isoA i, idx_j = isoA j, idx_l = isoA l.
  -- Then p idx_i = 2 * (extract_even_perm i), etc.
  -- So p idx_i + p idx_l = 2 * p idx_j.
  -- Also i < j < l implies idx_i < idx_j < idx_l because isoA is order preserving.
  -- Thus idx_i, idx_j, idx_l form a 3AP in p, which contradicts hp_free.
  -- By definition of `extract_even_perm`, we know that $(p (isoA i)).val = 2 * (extract_even_perm hs p hp_parity i).val$ and similarly for $j$ and $l$.
  have h_even_values : ∀ i : Fin k, (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i)).val = 2 * (extract_even_perm hs p hp_parity i).val := by
    intro i
    simp [extract_even_perm];
    have h_even_values : ∀ i : Fin k, (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i)).val % 2 = 0 := by
      grind;
    exact Eq.symm ( Nat.mul_div_cancel' ( Nat.dvd_of_mod_eq_zero ( h_even_values i ) ) );
  -- Since `isoA` is an order isomorphism, we have `isoA i < isoA j < isoA l`.
  have h_iso_lt : Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs i < Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j ∧ Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j < Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs l := by
    exact ⟨ by simpa using hij, by simpa using hjl ⟩;
  exact hp_free _ _ _ h_iso_lt.1 h_iso_lt.2 ( by linarith! [ h_even_values i, h_even_values j, h_even_values l ] )

/-
Bundles `extract_odd_map` into a permutation and proves it is 3AP-free.
-/
noncomputable def extract_odd_perm {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 1)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp : ∀ i, (p i : ℕ) % 2 = s i) : Equiv.Perm (Fin k) :=
  Equiv.ofBijective (extract_odd_map hs p hp) (by
    have h_inj := extract_odd_map_injective hs p hp
    exact ⟨h_inj, Finite.injective_iff_surjective.mp h_inj⟩)

lemma extract_odd_map_isThreeAPFree {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 1)).card = k)
    (p : Equiv.Perm (Fin (2 * k))) (hp_free : IsThreeAPFree p) (hp_parity : ∀ i, (p i : ℕ) % 2 = s i) :
    IsThreeAPFree (extract_odd_perm hs p hp_parity) := by
  intro i j l hij hjl h_eq
  -- Similar to the even case.
  -- Let B be the set of indices where s i = 1.
  -- Let isoB be the order isomorphism from Fin k to B.
  -- Let idx_i = isoB i, idx_j = isoB j, idx_l = isoB l.
  -- Then p idx_i = 2 * (extract_odd_perm i) + 1, etc.
  -- So p idx_i + p idx_l = 2 * p idx_j.
  -- Also i < j < l implies idx_i < idx_j < idx_l because isoB is order preserving.
  -- Thus idx_i, idx_j, idx_l form a 3AP in p, which contradicts hp_free.
  have h_contradiction : (p (Finset.orderIsoOfFin (Finset.filter (fun i => s i = 1) Finset.univ) hs i) : ℕ) + 1 + (p (Finset.orderIsoOfFin (Finset.filter (fun i => s i = 1) Finset.univ) hs l) : ℕ) + 1 = 2 * ((p (Finset.orderIsoOfFin (Finset.filter (fun i => s i = 1) Finset.univ) hs j) : ℕ) + 1) := by
    unfold extract_odd_perm at h_eq;
    unfold extract_odd_map at h_eq;
    grind;
  have := hp_free ( Finset.orderIsoOfFin ( Finset.filter ( fun i => s i = 1 ) Finset.univ ) hs i ) ( Finset.orderIsoOfFin ( Finset.filter ( fun i => s i = 1 ) Finset.univ ) hs j ) ( Finset.orderIsoOfFin ( Finset.filter ( fun i => s i = 1 ) Finset.univ ) hs l ) ?_ ?_ <;> simp_all +decide [ mul_add, add_assoc ];
  exact this ( by linarith )

/-
If the number of 0s in `s` is `k`, then the number of 1s is also `k`.
-/
lemma card_filter_odd_eq_k {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k) :
    (Finset.univ.filter (fun i => s i = 1)).card = k := by
      have h_card : (Finset.univ.filter (fun i => s i = 0)).card + (Finset.univ.filter (fun i => s i = 1)).card = 2 * k := by
        rw [ Finset.card_filter, Finset.card_filter ];
        rw [ ← Finset.sum_add_distrib, Finset.sum_congr rfl fun i _ => by rcases s i with ( _ | _ | s ) <;> trivial, Finset.sum_const, Finset.card_fin ] ; norm_num;
      linarith

/-
Decomposes a 3AP-free permutation with parity pattern `s` into two 3AP-free permutations of half the size.
-/
noncomputable def decompose_perm {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k)
    (p : { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s i }) :
    { p : Equiv.Perm (Fin k) // IsThreeAPFree p } × { p : Equiv.Perm (Fin k) // IsThreeAPFree p } :=
  let hs' : (Finset.univ.filter (fun i => s i = 1)).card = k := card_filter_odd_eq_k hs
  let p_even := extract_even_perm hs p.val p.prop.2
  let p_odd := extract_odd_perm hs' p.val p.prop.2
  have h_even_free := extract_even_map_isThreeAPFree hs p.val p.prop.1 p.prop.2
  have h_odd_free := extract_odd_map_isThreeAPFree hs' p.val p.prop.1 p.prop.2
  (⟨p_even, h_even_free⟩, ⟨p_odd, h_odd_free⟩)

/-
The decomposition map is injective.
-/
lemma decompose_perm_injective {k : ℕ} {s : Fin (2 * k) → Fin 2} (hs : (Finset.univ.filter (fun i => s i = 0)).card = k) :
    Function.Injective (decompose_perm (hs := hs)) := by
  intro p1 p2 h
  simp [decompose_perm] at h
  rcases h with ⟨h_even, h_odd⟩
  apply Subtype.ext
  apply Equiv.ext
  intro i
  -- We need to show p1 i = p2 i.
  -- We split into cases based on s i.
  by_cases h_si : s i = 0
  · -- If s i = 0, then i is in the domain of extract_even_perm.
    -- We use h_even to show p1 i = p2 i.
    -- Let A be the set of indices where s i = 0.
    -- i \in A. Let j = isoA.symm ⟨i, ...⟩.
    -- Then p1 i = 2 * (p_even j) and p2 i = 2 * (p_even j).
    -- Since $s i = 0$, we have $p1 i = 2 * extract_even_perm hs p1.val p1.prop.2 j$ and $p2 i = 2 * extract_even_perm hs p2.val p2.prop.2 j$ for some $j$.
    obtain ⟨j, hj⟩ : ∃ j : Fin k, i = Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j := by
      have h_exists_j : i ∈ Finset.univ.filter (fun i => s i = 0) := by
        aesop;
      have := Finset.mem_image.mp ( show i ∈ Finset.image ( fun j : Fin k => ( Finset.orderIsoOfFin ( Finset.filter ( fun i => s i = 0 ) Finset.univ ) hs j : Fin ( 2 * k ) ) ) Finset.univ from by
                                      simp +zetaDelta at *;
                                      exact h_exists_j ) ; aesop;
    have h_eq_even : ∀ (p : Equiv.Perm (Fin (2 * k))) (hp : IsThreeAPFree p) (hp_parity : ∀ i, (p i : ℕ) % 2 = s i), ∀ j : Fin k, (p (Finset.orderIsoOfFin (Finset.univ.filter (fun i => s i = 0)) hs j)).val = 2 * (extract_even_perm hs p hp_parity j).val := by
      intros p hp hp_parity j
      simp [extract_even_perm];
      exact Eq.symm ( Nat.mul_div_cancel' ( Nat.dvd_of_mod_eq_zero ( by have := hp_parity ( Finset.orderIsoOfFin ( Finset.univ.filter ( fun i => s i = 0 ) ) hs j ) ; have := Finset.mem_filter.mp ( Finset.orderIsoOfFin ( Finset.univ.filter ( fun i => s i = 0 ) ) hs j |>.2 ) ; aesop ) ) );
    grind
  · -- If s i = 1, then i is in the domain of extract_odd_perm.
    -- We use h_odd to show p1 i = p2 i.
    -- Let B be the set of indices where s i = 1.
    -- i \in B. Let j = isoB.symm ⟨i, ...⟩.
    -- Then p1 i = 2 * (p_odd j) + 1 and p2 i = 2 * (p_odd j) + 1.
    -- Since $s i = 1$,  we have $(p1.val i).val = 2 * (extract_odd_map (card_filter_odd_eq_k hs) p1.val p1.prop.2 j).val + 1$ and $(p2.val i).val = 2 * (extract_odd_map (card_filter_odd_eq_k hs) p2.val p2.prop.2 j).val + 1$ for some $j$.
    obtain ⟨j, hj⟩ : ∃ j : Fin k, i = (Finset.univ.filter (fun i => s i = 1)).orderIsoOfFin (card_filter_odd_eq_k hs) j := by
      have h_orderIso : ∀ x : Fin (2 * k), s x = 1 → ∃ j : Fin k, x = (Finset.univ.filter (fun i => s i = 1)).orderIsoOfFin (card_filter_odd_eq_k hs) j := by
        intro x hx
        have h_orderIso : x ∈ Finset.univ.filter (fun i => s i = 1) := by
          aesop;
        have := Finset.mem_image.mp ( show x ∈ Finset.image ( fun j : Fin k => ( Finset.orderIsoOfFin ( Finset.filter ( fun i => s i = 1 ) Finset.univ ) ( card_filter_odd_eq_k hs ) j : Fin ( 2 * k ) ) ) Finset.univ from by aesop ) ; aesop;
      exact h_orderIso i ( Or.resolve_left ( Fin.exists_fin_two.mp ( by tauto ) ) h_si );
    have h_parity_eq : (extract_odd_map (card_filter_odd_eq_k hs) p1.val p1.prop.2 j).val = (extract_odd_map (card_filter_odd_eq_k hs) p2.val p2.prop.2 j).val := by
      convert congr_arg ( fun f : Equiv.Perm ( Fin k ) => f j ) h_odd using 1;
      simp +decide [ Fin.ext_iff, extract_odd_perm ];
    unfold extract_odd_map at h_parity_eq;
    grind

/-
For a fixed parity pattern `s` with `k` zeros, the number of 3AP-free permutations matching `s` is at most `theta(k)^2`.
-/
lemma count_le_theta_sq (k : ℕ) (s : Fin (2 * k) → Fin 2) (hs : (Finset.univ.filter (fun i => s i = 0)).card = k) :
    Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s i } ≤ theta k ^ 2 := by
      -- Apply the decomposition map to each permutation in the set.
      have h_decomp : Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s i } ≤ Fintype.card ({ p : Equiv.Perm (Fin k) // IsThreeAPFree p } × { p : Equiv.Perm (Fin k) // IsThreeAPFree p }) := by
        convert Fintype.card_le_of_injective _ ( decompose_perm_injective ( hs := hs ) ) using 1;
      simpa [ sq ] using h_decomp

/-
For a fixed parity pattern `s` with `k` zeros, the number of 3AP-free permutations matching `s` is at most `theta(k)^2`.
-/
lemma count_le_theta_sq' (k : ℕ) (s : Fin (2 * k) → Fin 2) (hs : (Finset.univ.filter (fun i => s i = 0)).card = k) :
    Fintype.card { p : Equiv.Perm (Fin (2 * k)) // IsThreeAPFree p ∧ ∀ i, (p i : ℕ) % 2 = s i } ≤ theta k ^ 2 := by
      convert count_le_theta_sq k s hs using 1

/-
A parity pattern `s` is a valid balanced type if it has `k` zeros and is valid.
-/
def ValidBalancedType (k : ℕ) (s : Fin (2 * k) → Fin 2) : Prop :=
  (Finset.univ.filter (fun i => s i = 0)).card = k ∧ ValidType (2 * k) s

/-
The set of valid balanced parity patterns of length 2k.
-/
def validBalancedTypes (k : ℕ) : Finset (Fin (2 * k) → Fin 2) :=
  Finset.univ.filter (ValidBalancedType k)

/-
b_t(m) is the (m * 2^t)-th root of theta(m * 2^t).
-/
noncomputable def b (m t : ℕ) : ℝ := (theta (m * 2 ^ t) : ℝ) ^ (1 / (m * 2 ^ t : ℝ))

/-
The Sharma bound states that for k >= 1, theta(2k) <= 21 * theta(k)^2.
-/
def SharmaBound : Prop := ∀ k : ℕ, k ≥ 1 → theta (2 * k) ≤ 21 * theta k ^ 2

/-
The sequence b_t(m) satisfies the lower bound recurrence:
2^(1/(m*2^(t+1))) * b_t(m) <= b_{t+1}(m).
-/
lemma b_recurrence_lower (m t : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) :
    (2 : ℝ) ^ (1 / (m * 2 ^ (t + 1) : ℝ)) * b m t ≤ b m (t + 1) := by
      let _ := h_pos
      have h_lower_bound : ∀ k : ℕ, 1 ≤ k → (2 : ℝ) ^ (1 / (2 * k : ℝ)) * ((theta k : ℝ) ^ (1 / (k : ℝ))) ≤ (theta (2 * k) : ℝ) ^ (1 / (2 * k : ℝ)) := by
        intro k hk
        have h_lower_bound : (2 : ℝ) * theta k ^ 2 ≤ theta (2 * k) := by
          exact_mod_cast theta_two_mul_le k hk
        generalize_proofs at *;
        convert Real.rpow_le_rpow ( by positivity ) h_lower_bound _ using 1;
        · rw [ Real.mul_rpow ( by positivity ) ( by positivity ), ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ) ] ; ring_nf;
        · positivity
      generalize_proofs at *;
      convert h_lower_bound ( m * 2 ^ t ) ( Nat.mul_pos hm ( pow_pos ( by decide ) _ ) ) using 1 <;> push_cast [ b ] <;> ring_nf

/-
The sequence b_t(m) satisfies the upper bound recurrence:
b_{t+1}(m) <= 21^(1/(m*2^(t+1))) * b_t(m).
-/
lemma b_recurrence_upper (m t : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound) :
    b m (t + 1) ≤ (21 : ℝ) ^ (1 / (m * 2 ^ (t + 1) : ℝ)) * b m t := by
      let _ := h_pos
      -- Let k = m * 2^t. Then 2k = m * 2^(t+1).
      set k : ℕ := m * 2 ^ t
      have h2k : 2 * k = m * 2 ^ (t + 1) := by
        ring;
      -- By the Sharma bound, we have theta(2k) ≤ 21 * theta(k)^2.
      have h_theta_bound : theta (2 * k) ≤ 21 * theta k ^ 2 := by
        exact h_sharma k ( Nat.mul_pos hm ( pow_pos ( by decide ) _ ) );
      -- Taking the (2k)-th root of both sides of the inequality theta(2k) ≤ 21 * theta(k)^2, we get b_t(m) ≤ 21^(1/(m*2^t)) * b_t(m).
      have h_root : (theta (2 * k) : ℝ) ^ (1 / (2 * k : ℝ)) ≤ (21 : ℝ) ^ (1 / (2 * k : ℝ)) * (theta k : ℝ) ^ (2 / (2 * k : ℝ)) := by
        convert Real.rpow_le_rpow ( by positivity ) ( show ( theta ( 2 * k ) : ℝ ) ≤ 21 * theta k ^ 2 by exact_mod_cast h_theta_bound ) ( by positivity : ( 0 : ℝ ) ≤ 1 / ( 2 * k ) ) using 1 ; rw [ Real.mul_rpow ( by positivity ) ( by positivity ), ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ) ] ; ring_nf;
      convert h_root using 1 <;> norm_num [ b ] ; ring_nf;
      · norm_num +zetaDelta at *;
        norm_num [ ← inv_pow ];
      · grind

/-
The sequence b_t(m) is strictly increasing.
-/
lemma b_monotone (m : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) :
    StrictMono (b m) := by
      refine' strictMono_nat_of_lt_succ _;
      intro n
      have h_lower : b m (n + 1) ≥ (2 : ℝ) ^ (1 / (m * 2 ^ (n + 1) : ℝ)) * b m n := by
        exact b_recurrence_lower m n hm h_pos;
      refine' lt_of_lt_of_le _ h_lower;
      exact lt_mul_of_one_lt_left ( Real.rpow_pos_of_pos ( Nat.cast_pos.mpr ( h_pos _ ) ) _ ) ( Real.one_lt_rpow ( by norm_num ) ( by positivity ) )

/-
The sequence b_t(m) is bounded above.
-/
lemma b_bounded_above (m : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound) :
    BddAbove (Set.range (b m)) := by
      use b m 0 * 21 ^ (1 / m : ℝ);
      rintro x ⟨ t, rfl ⟩;
      -- By induction on $t$, we can show that $b_t(m) \leq b_0(m) * 21^{1/m}$ for all $t$. The base case is when $t = 0$.
      have h_inductive_step : ∀ t : ℕ, b m (t + 1) ≤ (21 : ℝ) ^ (1 / (m * 2 ^ (t + 1) : ℝ)) * b m t := by
        exact fun t ↦ b_recurrence_upper m t hm h_pos h_sharma;
      -- By induction on $t$, we can show that $b_t(m) \leq b_0(m) * 21^{1/m}$ for all $t$. The base case is when $t = 0$, which is trivial.
      have h_inductive_bound : ∀ t : ℕ, b m t ≤ b m 0 * (21 : ℝ) ^ (∑ j ∈ Finset.range t, (1 / (m * 2 ^ (j + 1) : ℝ))) := by
        intro t
        induction' t with t ih;
        · norm_num;
        · convert le_trans ( h_inductive_step t ) ( mul_le_mul_of_nonneg_left ih ( by positivity ) ) using 1 ; rw [ Finset.sum_range_succ ] ; rw [ Real.rpow_add ( by positivity ) ] ; ring;
      refine le_trans ( h_inductive_bound t ) ?_;
      gcongr;
      · exact Real.rpow_nonneg ( Nat.cast_nonneg _ ) _;
      · norm_num;
      · ring_nf;
        rw [ ← Finset.sum_mul _ _ _ ] ; rw [ ← Finset.mul_sum _ _ _ ] ; rw [ geom_sum_eq ] <;> ring_nf <;> norm_num

/-
The sequence b_t(m) converges to some limit L.
-/
lemma b_converges (m : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound) :
    ∃ L, Filter.Tendsto (b m) Filter.atTop (nhds L) := by
      have h_bounded : BddAbove (Set.range (b m)) := by
        exact b_bounded_above m hm h_pos h_sharma;
      exact ⟨ _, tendsto_atTop_isLUB ( b_monotone m hm h_pos |> StrictMono.monotone ) ( isLUB_ciSup h_bounded ) ⟩

/-
L_m is the limit of the sequence b_t(m).
-/
noncomputable def L (m : ℕ) : ℝ := lim (Filter.atTop.map (b m))

lemma b_tendsto_L (m : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound) :
    Filter.Tendsto (b m) Filter.atTop (nhds (L m)) := by
      convert b_converges m hm h_pos h_sharma |> Classical.choose_spec;
      rw [ eq_comm ];
      have := Classical.choose_spec ( b_converges m hm h_pos h_sharma );
      exact tendsto_nhds_unique this ( Classical.epsilon_spec ( show ∃ x, Filter.Tendsto ( b m ) Filter.atTop ( nhds x ) from ⟨ _, this ⟩ ) )

/-
L_m is bounded by (2*theta(m*2^t))^(1/(m*2^t)) and (21*theta(m*2^t))^(1/(m*2^t)).
-/
lemma L_bounds (m t : ℕ) (hm : m ≥ 1) (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound) :
    (2 * theta (m * 2 ^ t) : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) ≤ L m ∧
    L m ≤ (21 * theta (m * 2 ^ t) : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) := by
      constructor;
      · have h_lim_inf : Filter.Tendsto (fun k => (2 : ℝ) ^ ((1 - 2⁻¹ ^ k) / (m * 2 ^ t : ℝ)) * b m t) Filter.atTop (nhds ((2 : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) * b m t)) := by
          exact le_trans ( Filter.Tendsto.mul ( tendsto_const_nhds.rpow ( Filter.Tendsto.div_const ( tendsto_const_nhds.sub ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by norm_num ) ( by norm_num ) ) ) _ ) ( by norm_num ) ) tendsto_const_nhds ) ( by norm_num );
        have h_lim_inf_le : ∀ k, (2 : ℝ) ^ ((1 - 2⁻¹ ^ k) / (m * 2 ^ t : ℝ)) * b m t ≤ b m (t + k) := by
          intro k
          induction' k with k ih;
          · norm_num;
          · have h_recurrence : b m (t + k + 1) ≥ (2 : ℝ) ^ (1 / (m * 2 ^ (t + k + 1) : ℝ)) * b m (t + k) := by
              exact b_recurrence_lower m (t + k) hm h_pos;
            convert le_trans _ h_recurrence using 1;
            convert mul_le_mul_of_nonneg_left ih ( Real.rpow_nonneg zero_le_two _ ) using 1 ; ring_nf;
            norm_num [ mul_assoc, ← Real.rpow_add ] ; ring_nf;
        have h_lim_inf_le : (2 : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) * b m t ≤ L m := by
          exact le_of_tendsto_of_tendsto' h_lim_inf ( b_tendsto_L m hm h_pos h_sharma |> Filter.Tendsto.comp <| Filter.tendsto_atTop_mono ( fun k => Nat.le_add_left _ _ ) Filter.tendsto_id ) h_lim_inf_le;
        convert h_lim_inf_le using 1 ; rw [ Real.mul_rpow ( by positivity ) ( by positivity ) ] ; norm_num [ b ];
      · -- By the upper bound recurrence relation, we have $b_{t+k}(m) \leq 21^{(1-2^{-k})/(m2^t)} b_t(m)$.
        have h_upper_bound : ∀ k : ℕ, b m (t + k) ≤ (21 : ℝ) ^ ((1 - 2⁻¹ ^ k) / (m * 2 ^ t : ℝ)) * b m t := by
          intro k
          induction' k with k ih;
          · norm_num;
          · have := b_recurrence_upper m ( t + k ) ( by linarith ) ( fun n => h_pos n ) h_sharma;
            convert le_trans this ( mul_le_mul_of_nonneg_left ih <| by positivity ) using 1 ; ring_nf;
            norm_num [ mul_assoc, ← Real.rpow_add ] ; ring_nf;
        -- Taking the limit as $k \to \infty$, we get $L_m \leq 21^{1/(m2^t)} b_t(m)$.
        have h_upper_limit : Filter.Tendsto (fun k => (21 : ℝ) ^ ((1 - 2⁻¹ ^ k) / (m * 2 ^ t : ℝ)) * b m t) Filter.atTop (nhds ((21 : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) * b m t)) := by
          exact le_trans ( Filter.Tendsto.mul ( tendsto_const_nhds.rpow ( Filter.Tendsto.div_const ( tendsto_const_nhds.sub ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by norm_num ) ( by norm_num ) ) ) _ ) ( by norm_num ) ) tendsto_const_nhds ) ( by norm_num );
        have h_upper_limit : L m ≤ (21 : ℝ) ^ (1 / (m * 2 ^ t : ℝ)) * b m t := by
          exact le_of_tendsto_of_tendsto' ( b_tendsto_L m hm h_pos h_sharma |> Filter.Tendsto.comp <| Filter.tendsto_atTop_mono ( fun k => Nat.le_add_left _ _ ) Filter.tendsto_id ) h_upper_limit fun k => h_upper_bound k;
        convert h_upper_limit using 1;
        rw [ Real.mul_rpow ( by positivity ) ( by positivity ), b ]

/-
The inequality (2 * theta(64))^(1/64) > (21 * theta(75))^(1/75) holds.
-/
def theta_64_val_num : ℕ := 39911512393313043466768
def theta_75_val_num : ℕ := 30235147387260979648843264

lemma separation_inequality :
    (2 * theta_64_val_num : ℝ) ^ (1 / 64 : ℝ) > (21 * theta_75_val_num : ℝ) ^ (1 / 75 : ℝ) := by
      rw [ gt_iff_lt, Real.rpow_def_of_pos, Real.rpow_def_of_pos ] <;> norm_num;
      · field_simp;
        rw [ mul_comm, ← Real.log_rpow, ← Real.log_rpow, Real.log_lt_log_iff ] <;> norm_cast;
      · native_decide +revert;
      · native_decide +revert

/-
L(1) is strictly greater than L(75).
-/
lemma L_1_gt_L_75 (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound)
    (h64 : theta 64 = theta_64_val_num) (h75 : theta 75 = theta_75_val_num) :
    L 1 > L 75 := by
      -- By definition of $L_m$, we have $L_1 \geq (2 \theta(64))^{1/64}$ and $L_{75} \leq (21 \theta(75))^{1/75}$.
      have hL1 : L 1 ≥ (2 * theta 64 : ℝ) ^ (1 / 64 : ℝ) := by
        -- Apply the L_bounds lemma with m=1 and t=6.
        have hL1 : (2 * theta 64 : ℝ) ^ (1 / 64 : ℝ) ≤ L 1 := by
          have := L_bounds 1 6 (by norm_num) h_pos h_sharma
          exact_mod_cast this.1;
        exact RCLike.ofReal_le_ofReal.mp hL1
      have hL75 : L 75 ≤ (21 * theta 75 : ℝ) ^ (1 / 75 : ℝ) := by
        have := L_bounds 75 0 ( by norm_num ) h_pos h_sharma; norm_num at * ; linarith!;
      -- By combining the inequalities from hL1 and hL75, we can conclude that L(1) > L(75).
      have h_final : (2 * theta 64 : ℝ) ^ (1 / 64 : ℝ) > (21 * theta 75 : ℝ) ^ (1 / 75 : ℝ) := by
        rw [ h64, h75 ] ; exact mod_cast separation_inequality;
      linarith

/-
The limit of theta(n)^(1/n) does not exist.
-/
noncomputable def growth_rate (n : ℕ) : ℝ := (theta n : ℝ) ^ (1 / n : ℝ)

theorem main_theorem (h_pos : ∀ n, 0 < theta n) (h_sharma : SharmaBound)
    (h64 : theta 64 = theta_64_val_num) (h75 : theta 75 = theta_75_val_num) :
    ¬ ∃ L, Filter.Tendsto growth_rate Filter.atTop (nhds L) := by
      -- Suppose the limit exists and is L.
      by_contra h_contra
      obtain ⟨L, hL⟩ := h_contra;
      -- Then every subsequence must converge to L.
      have h_subseq : Filter.Tendsto (fun t => b 1 t) Filter.atTop (nhds L) ∧ Filter.Tendsto (fun t => b 75 t) Filter.atTop (nhds L) := by
        constructor;
        · convert hL.comp ( show Filter.Tendsto ( fun t => 2 ^ t ) Filter.atTop Filter.atTop from tendsto_pow_atTop_atTop_of_one_lt one_lt_two ) using 2;
          unfold b growth_rate; aesop;
        · convert hL.comp ( show Filter.Tendsto ( fun t => 75 * 2 ^ t ) Filter.atTop Filter.atTop from ?_ ) using 2;
          · unfold b growth_rate; aesop;
          · exact Filter.tendsto_atTop_mono ( fun t => by linarith [ Nat.one_le_pow t 2 zero_lt_two ] ) ( tendsto_pow_atTop_atTop_of_one_lt one_lt_two );
      exact absurd ( tendsto_nhds_unique h_subseq.1 ( b_tendsto_L 1 ( by norm_num ) h_pos h_sharma ) ) ( by linarith [ tendsto_nhds_unique h_subseq.2 ( b_tendsto_L 75 ( by norm_num ) h_pos h_sharma ), L_1_gt_L_75 h_pos h_sharma h64 h75 ] )
